"""add vdot to athlete profile

Revision ID: 3a6c21c88a4f
Revises: bdd0c94a2611
Create Date: 2026-10-07 17:13:54.531845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a6c21c88a4f'
down_revision: Union[str, Sequence[str], None] = 'bdd0c94a2611'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('athlete_profiles', sa.Column('vdot', sa.Float(), nullable=True))
    op.add_column('athlete_profiles', sa.Column('best_effort_distance_m', sa.Float(), nullable=True))
    op.add_column('athlete_profiles', sa.Column('best_effort_time_s', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('athlete_profiles', 'best_effort_time_s')
    op.drop_column('athlete_profiles', 'best_effort_distance_m')
    op.drop_column('athlete_profiles', 'vdot')
    # ### end Alembic commands ###
