"""initial schema

Revision ID: bdd0c94a2611
Revises: 
Create Date: 2026-10-07 15:58:39.134335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdd0c94a2611'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('telegram_chat_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('garmin_linked', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_app_users'))
    )
    op.create_index(op.f('ix_app_users_telegram_chat_id'), 'app_users', ['telegram_chat_id'], unique=True)
    op.create_table('athlete_profiles',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('raw_summary_text', sa.Text(), nullable=True),
    sa.Column('average_weekly_km', sa.Float(), nullable=True),
    sa.Column('max_heart_rate', sa.Integer(), nullable=True),
    sa.Column('typical_easy_heart_rate', sa.Integer(), nullable=True),
    sa.Column('garmin_vo2_max', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_users.id'], name=op.f('fk_athlete_profiles_user_id_app_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_athlete_profiles')),
    sa.UniqueConstraint('user_id', name=op.f('uq_athlete_profiles_user_id'))
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('user', 'assistant')", name=op.f('ck_chat_messages_role_valid')),
    sa.ForeignKeyConstraint(['user_id'], ['app_users.id'], name=op.f('fk_chat_messages_user_id_app_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_messages'))
    )
    op.create_index('ix_chat_messages_user_created', 'chat_messages', ['user_id', 'created_at'], unique=False)
    op.create_table('processed_activities',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('garmin_activity_id', sa.String(length=100), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_users.id'], name=op.f('fk_processed_activities_user_id_app_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_processed_activities')),
    sa.UniqueConstraint('user_id', 'garmin_activity_id', name='uq_processed_activities_user_activity')
    )
    op.create_table('training_plans',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('target_race', sa.String(length=255), nullable=False),
    sa.Column('race_date', sa.Date(), nullable=False),
    sa.Column('total_weeks', sa.Integer(), nullable=False),
    sa.Column('plan_details', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('total_weeks > 0', name=op.f('ck_training_plans_total_weeks_positive')),
    sa.ForeignKeyConstraint(['user_id'], ['app_users.id'], name=op.f('fk_training_plans_user_id_app_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_training_plans'))
    )
    op.create_index('ix_training_plans_user_id', 'training_plans', ['user_id'], unique=False)
    op.create_index('uq_training_plans_one_active_per_user', 'training_plans', ['user_id'], unique=True, postgresql_where=sa.text('active'))
    op.create_table('weekly_plans',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('training_plan_id', sa.BigInteger(), nullable=False),
    sa.Column('week_start_date', sa.Date(), nullable=False),
    sa.Column('week_end_date', sa.Date(), nullable=False),
    sa.Column('plan_details', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('week_end_date >= week_start_date', name=op.f('ck_weekly_plans_week_range_valid')),
    sa.ForeignKeyConstraint(['training_plan_id'], ['training_plans.id'], name=op.f('fk_weekly_plans_training_plan_id_training_plans'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['app_users.id'], name=op.f('fk_weekly_plans_user_id_app_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_weekly_plans')),
    sa.UniqueConstraint('training_plan_id', 'week_start_date', name='uq_weekly_plans_plan_week')
    )
    op.create_index('ix_weekly_plans_user_week', 'weekly_plans', ['user_id', 'week_start_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_weekly_plans_user_week', table_name='weekly_plans')
    op.drop_table('weekly_plans')
    op.drop_index('uq_training_plans_one_active_per_user', table_name='training_plans', postgresql_where=sa.text('active'))
    op.drop_index('ix_training_plans_user_id', table_name='training_plans')
    op.drop_table('training_plans')
    op.drop_table('processed_activities')
    op.drop_index('ix_chat_messages_user_created', table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_table('athlete_profiles')
    op.drop_index(op.f('ix_app_users_telegram_chat_id'), table_name='app_users')
    op.drop_table('app_users')
    # ### end Alembic commands ###
